import { motion } from 'framer-motion';

const steps = [
  {
    title: 'Digital Media Is Changing',
    description: 'Every day, millions of images, videos, and audio files are generated by AI — indistinguishable from reality.',
    icon: '🌐',
  },
  {
    title: 'AI Generated Content Is Rising',
    description: 'Deepfakes, voice clones, and manipulated media now threaten the integrity of communication worldwide.',
    icon: '⚠️',
  },
  {
    title: 'Authentix Protects Digital Trust',
    description: 'Our multi-signal AI fusion engine analyzes media in real time, scoring authenticity with unmatched precision.',
    icon: '🛡️',
  },
];

const ScrollStory = () => {
  return (
    <section className="section-padding relative overflow-hidden">
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/3 left-0 w-[300px] h-[300px] bg-secondary/5 blur-[100px] rounded-full" />
      </div>

      <div className="max-w-4xl mx-auto space-y-32">
        {steps.map((step, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 60 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-100px' }}
            transition={{ duration: 0.8, delay: 0.1 }}
            className="text-center"
          >
            <div className="text-5xl mb-6">{step.icon}</div>
            <h2 className="font-display text-3xl sm:text-4xl font-bold mb-4 text-foreground">
              {step.title}
            </h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto leading-relaxed">
              {step.description}
            </p>
            {i < steps.length - 1 && (
              <div className="mt-12 flex justify-center">
                <div className="w-px h-20 bg-gradient-to-b from-primary/40 to-transparent" />
              </div>
            )}
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default ScrollStory;
